"""gen indexes

Revision ID: 3fed549b4455
Revises: cd870344a260
Create Date: 2026-02-24 10:16:36.183310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fed549b4455"
down_revision: str | Sequence[str] | None = "cd870344a260"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index("idx_building_coords", "building", ["latitude", "longitude"], unique=False)
    op.create_index(
        "idx_org_name_trgm",
        "organisation",
        [sa.literal_column("name gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_org_name_trgm", table_name="organisation", postgresql_using="gin")
    op.drop_index("idx_building_coords", table_name="building")
    op.drop_index("idx_org_name_trgm", table_name="organisation")
    # ### end Alembic commands ###
